### ISSUE TITLE
Book Member

### ISSUE THREAD

**Issue by nklapste** [CMPUT291PROJECT1F18/Mini-Project-1#10]
The member should be able to book other members on the rides they offer. Your system should list all rides the member offers with the number of available seats for each ride (i.e., seats that are not booked). If there are more than 5 matching rides, at most 5 will be shown at a time, and the member will have the option to see more. The member should be able to select a ride and book a member for that ride by entering the member email, the number of seats booked, the cost per seat, and pickup and drop off location codes. Your system should assign a unique booking number (bno) to the booking. Your system should give a warning if a ride is being overbooked (i.e. the number of seats booked exceeds the number of seats offered), but will allow overbooking if the member confirms it. After a successful booking, a proper message should be sent to the other member that s/he is booked on the ride.

**Comment by ryfurrer** [comment]
Waiting on #55
