### ISSUE TITLE
Login method

### ISSUE THREAD

**Issue by nklapste** [CMPUT291PROJECT1F18/Mini-Project-1#3]
The first screen of your system should provide options for members to login and for new members to register. Existing members should be able to login using a valid email and password, denoted with email and pwd in table members. After a login, all unseen messages of the member will be displayed, and the status of the messages will be set to seen (i.e, the seen column is set to 'y'). Unregistered members should be able to sign up by providing a unique email, a name, a phone, and a password. Proper messages should be given if the provided email is not unique. After a successful login or signup, members should be able to perform the subsequent operations (possibly chosen from a menu) as discussed next.

The login password non-visible at the time of typing.

**Comment by nklapste** [comment]
Currently after registering the cli program exits. It is expected the user starts a shell startup command `mini-project-1` to login and interact with the database. Is this acceptable @ryfurrer @thomaslorincz .

**Comment by ryfurrer** [comment]
@nklapste That is acceptable. But when I start mini project 1, I need to be able to register or login. Currently it goes straight to login

**Comment by nklapste** [comment]
Currently all messages are being viewed on `show_inbox`

should we change that so that it only shows non viewed messages?

**Comment by nklapste** [comment]
I believe all functionality is complete for login/logout/registering.

Closing issue.
