### ISSUE TITLE
Limit ride requests search to 5 results

### ISSUE THREAD

**Issue by thomaslorincz** [CMPUT291PROJECT1F18/Mini-Project-1#35]
Limit ride requests search to 5 results. Give some method for the user to have the rest outputted.

**Comment by ryfurrer** [comment]
Is this a query limit or in displaying results?
If it’s just for displaying results note get selection from ride.py:
def get_selection(items: list):
    """
    Gets the user to select a item from a list, displaying up to 5 items at a time.
    :param items: list of items
    :return: selected item from items
    """
