### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by ryfurrer** [CMPUT291PROJECT1F18/Mini-Project-1#57]
txt template in docs

The design document should include 
(a) a general overview of your system with a small user guide, 
(b) a detailed design of your software with a focus on the components required to 
deliver the major functions of your application, 
(c) your testing strategy, and 
(d) your group work break-down strategy. 

Everyone at least needs to put down their time spent (an estimate) and progress made

**Comment by nklapste** [comment]
testing strategy is likely just white-box unit testing.
